FROM balenalib/%%BALENA_ARCH%%-debian-python:3.9

WORKDIR /usr/src/app

COPY . .

RUN apt-get update
RUN apt-get install -y python3-rpi.gpio
RUN pip3 install -r requirements.txt

CMD ["python3", "server.py"]